openapi: 3.0.0
info:
  version: 1.0.0
  title: User
  contact: 
    email: asd@as.com
  description: 'User API'
tags:
  - name: user 
servers:
  - url: ''
security:
    - BasicAuth: []
paths:
  /user:
    get:
      description: 'Get details of a particular user'
      operationId: getUser
      tags:
        - user
      parameters:
        - name: id
          in: query
          description: ID of the user
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: 'Sample response: Details about a user by ID'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    post:
      description: 'Create a user'
      operationId: postUser
      tags:
        - user
      responses:
        '201':
          description: 'User has been successfully created'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '400':
          description: 'Bad request. Check data sent'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'          
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    User:
      type: object
      required:
        - id
        - name
        - dob
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        dob:
            type: string
            format: datetime
        tag:
          type: string
    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic